import { AuthContext } from 'context';
import Head from 'next/head';
import { useContext } from 'react';

export default function Home() {
  
  const { signout } = useContext(AuthContext);
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className='bg-blue-600 p-4 text-white' onClick={ signout }>
          Logout
        </button>
      </main>
    </div>
  );
}
